## Makefile Projeto 1 ERDA ##

all: prog

prog: matrizes.o lista.o main.o
	gcc -o prog matrizes.o lista.o main.o

matrizes.o: matrizes.c
	gcc -c matrizes.c

lista.o: lista.c
	gcc -c lista.c

main.o: main.c
	gcc -c main.c
